import { TelegramTheme } from './TelegramTheme';

export const dark: TelegramTheme = {
  windowBg: { value: '#1F2C36' },
  windowFg: { value: '#C5C5C5' },
  windowBgOver: { value: '#2A3C4A' },
  nullWindowBgOver: { value: '#095280' },
  windowBgRipple: { value: '#165F8D' },
  windowFgOver: { value: 'windowFg', ref: true },
  windowSubTextFg: { value: '#A8A8A8' },
  windowSubTextFgOver: { value: '#B8B8B8' },
  windowBoldFg: { value: '#C9C9C9' },
  windowBoldFgOver: { value: '#D9D9D9' },
  windowBgActive: { value: '#4FB0D6' },
  windowFgActive: { value: '#EDEDED' },
  windowActiveTextFg: { value: '#2599DC' },
  windowShadowFg: { value: '#B3B3B3' },
  windowShadowFgFallback: { value: '#042029' },
  shadowFg: { value: '#FFFFFF18' },
  slideFadeOutBg: { value: '#0000003c' },
  slideFadeOutShadowFg: { value: '#000000' },
  imageBg: { value: '#000000' },
  imageBgTransparent: { value: '#ffffff' },
  activeButtonBg: { value: 'windowBgActive', ref: true },
  activeButtonBgOver: { value: '#39a5db' },
  activeButtonBgRipple: { value: '#2C5A7D' },
  activeButtonFg: { value: 'windowFgActive', ref: true },
  activeButtonFgOver: { value: 'activeButtonFg', ref: true },
  activeButtonSecondaryFg: { value: '#cceeff' },
  activeButtonSecondaryFgOver: { value: 'activeButtonSecondaryFg', ref: true },
  activeLineFg: { value: '#37a1de' },
  activeLineFgError: { value: '#e48383' },
  lightButtonBg: { value: 'windowBg', ref: true },
  lightButtonBgOver: { value: '#45525C' },
  lightButtonBgRipple: { value: '#5F6C76' },
  lightButtonFg: { value: 'windowActiveTextFg', ref: true },
  lightButtonFgOver: { value: 'lightButtonFg', ref: true },
  attentionButtonFg: { value: '#d14e4e' },
  attentionButtonFgOver: { value: '#d14e4e' },
  attentionButtonBgOver: { value: '#fcdfde' },
  attentionButtonBgRipple: { value: '#f4c3c2' },
  outlineButtonBg: { value: 'windowBg', ref: true },
  outlineButtonBgOver: { value: 'lightButtonBgOver', ref: true },
  outlineButtonOutlineFg: { value: 'windowBgActive', ref: true },
  outlineButtonBgRipple: { value: 'lightButtonBgRipple', ref: true },
  menuBg: { value: 'windowBg', ref: true },
  menuBgOver: { value: 'nullWindowBgOver', ref: true },
  menuBgRipple: { value: 'windowBgRipple', ref: true },
  menuIconFg: { value: '#6C7983' },
  menuIconFgOver: { value: '#7B8892' },
  menuSubmenuArrowFg: { value: '#373737' },
  menuFgDisabled: { value: '#cccccc' },
  menuSeparatorFg: { value: '#f1f1f1' },
  scrollBarBg: { value: '#267db253' },
  scrollBarBgOver: { value: '#267db27a' },
  scrollBg: { value: '#267db21a' },
  scrollBgOver: { value: '#267db22c' },
  smallCloseIconFg: { value: '#c7c7c7' },
  smallCloseIconFgOver: { value: '#a3a3a3' },
  radialFg: { value: 'windowFgActive', ref: true },
  radialBg: { value: '#00000056' },
  placeholderFg: { value: '#47768E' },
  placeholderFgActive: { value: '#38677F' },
  inputBorderFg: { value: '#e0e0e0' },
  filterInputBorderFg: { value: '#54c3f3' },
  checkboxFg: { value: '#b3b3b3' },
  sliderBgInactive: { value: '#2D5066' },
  sliderBgActive: { value: 'windowBgActive', ref: true },
  tooltipBg: { value: '#eef2f5' },
  tooltipFg: { value: '#5d6c80' },
  tooltipBorderFg: { value: '#c9d1db' },
  titleBg: { value: 'nullWindowBgOver', ref: true },
  titleShadow: { value: '#00000003' },
  titleButtonFg: { value: '#ababab' },
  titleButtonBgOver: { value: '#e5e5e5' },
  titleButtonFgOver: { value: '#9a9a9a' },
  titleButtonCloseBgOver: { value: '#e81123' },
  titleButtonCloseFgOver: { value: 'windowFgActive', ref: true },
  titleFgActive: { value: '#85B4CC' },
  titleFg: { value: '#57869E' },
  trayCounterBg: { value: '#f23c34' },
  trayCounterBgMute: { value: '#888888' },
  trayCounterFg: { value: '#ffffff' },
  trayCounterBgMacInvert: { value: '#ffffff' },
  trayCounterFgMacInvert: { value: '#ffffff01' },
  layerBg: { value: '#0000007f' },
  cancelIconFg: { value: 'menuIconFg', ref: true },
  cancelIconFgOver: { value: 'menuIconFgOver', ref: true },
  boxBg: { value: 'windowBg', ref: true },
  boxTextFg: { value: 'windowFg', ref: true },
  boxTextFgGood: { value: '#4ab44a' },
  boxTextFgError: { value: '#d84d4d' },
  boxTitleFg: { value: 'windowBoldFg', ref: true },
  boxSearchBg: { value: 'boxBg', ref: true },
  boxSearchCancelIconFg: { value: 'cancelIconFg', ref: true },
  boxSearchCancelIconFgOver: { value: 'cancelIconFgOver', ref: true },
  boxTitleAdditionalFg: { value: '#808080' },
  boxTitleCloseFg: { value: 'cancelIconFg', ref: true },
  boxTitleCloseFgOver: { value: 'cancelIconFgOver', ref: true },
  membersAboutLimitFg: { value: 'windowSubTextFgOver', ref: true },
  contactsBg: { value: 'windowBg', ref: true },
  contactsBgOver: { value: 'nullWindowBgOver', ref: true },
  contactsNameFg: { value: 'boxTextFg', ref: true },
  contactsStatusFg: { value: 'windowSubTextFg', ref: true },
  contactsStatusFgOver: { value: 'windowSubTextFgOver', ref: true },
  contactsStatusFgOnline: { value: 'windowActiveTextFg', ref: true },
  photoCropFadeBg: { value: 'layerBg', ref: true },
  photoCropPointFg: { value: '#ffffff7f' },
  introBg: { value: 'windowBg', ref: true },
  introTitleFg: { value: 'windowBoldFg', ref: true },
  introDescriptionFg: { value: 'windowSubTextFg', ref: true },
  introErrorFg: { value: 'windowSubTextFg', ref: true },
  introCoverTopBg: { value: '#0f89d0' },
  introCoverBottomBg: { value: '#39b0f0' },
  introCoverIconsFg: { value: '#5ec6ff' },
  introCoverPlaneTrace: { value: '#5ec6ff69' },
  introCoverPlaneInner: { value: '#c6d8e8' },
  introCoverPlaneOuter: { value: '#a1bed4' },
  introCoverPlaneTop: { value: '#ffffff' },
  dialogsMenuIconFg: { value: 'menuIconFg', ref: true },
  dialogsMenuIconFgOver: { value: 'menuIconFgOver', ref: true },
  dialogsBg: { value: 'windowBg', ref: true },
  dialogsNameFg: { value: 'windowBoldFg', ref: true },
  dialogsChatIconFg: { value: 'dialogsNameFg', ref: true },
  dialogsDateFg: { value: 'windowSubTextFg', ref: true },
  dialogsTextFg: { value: 'windowSubTextFg', ref: true },
  dialogsTextFgService: { value: 'windowActiveTextFg', ref: true },
  dialogsDraftFg: { value: '#dd4b39' },
  dialogsVerifiedIconBg: { value: 'windowBgActive', ref: true },
  dialogsVerifiedIconFg: { value: 'windowFgActive', ref: true },
  dialogsSendingIconFg: { value: '#c1c1c1' },
  dialogsSentIconFg: { value: '#42a0db' },
  dialogsUnreadBg: { value: 'windowBgActive', ref: true },
  dialogsUnreadBgMuted: { value: '#6C7983' },
  dialogsUnreadFg: { value: '#DEDEDE' },
  dialogsBgOver: { value: 'nullWindowBgOver', ref: true },
  dialogsNameFgOver: { value: 'windowBoldFgOver', ref: true },
  dialogsChatIconFgOver: { value: 'dialogsNameFgOver', ref: true },
  dialogsDateFgOver: { value: 'windowSubTextFgOver', ref: true },
  dialogsTextFgOver: { value: 'windowSubTextFgOver', ref: true },
  dialogsTextFgServiceOver: { value: '#35A9EC' },
  dialogsDraftFgOver: { value: 'dialogsDraftFg', ref: true },
  dialogsVerifiedIconBgOver: { value: 'dialogsVerifiedIconBg', ref: true },
  dialogsVerifiedIconFgOver: { value: 'dialogsVerifiedIconFg', ref: true },
  dialogsSendingIconFgOver: { value: 'dialogsSendingIconFg', ref: true },
  dialogsSentIconFgOver: { value: 'dialogsSentIconFg', ref: true },
  dialogsUnreadBgOver: { value: 'dialogsUnreadBg', ref: true },
  dialogsUnreadBgMutedOver: { value: 'dialogsUnreadBgMuted', ref: true },
  dialogsUnreadFgOver: { value: 'dialogsUnreadFg', ref: true },
  dialogsBgActive: { value: '#38556B' },
  dialogsNameFgActive: { value: 'windowFgActive', ref: true },
  dialogsChatIconFgActive: { value: 'dialogsNameFgActive', ref: true },
  dialogsDateFgActive: { value: 'windowFgActive', ref: true },
  dialogsTextFgActive: { value: 'windowFgActive', ref: true },
  dialogsTextFgServiceActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsDraftFgActive: { value: '#c6e1f7' },
  dialogsVerifiedIconBgActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsVerifiedIconFgActive: { value: 'dialogsBgActive', ref: true },
  dialogsSendingIconFgActive: { value: '#ffffff99' },
  dialogsSentIconFgActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsUnreadBgActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsUnreadBgMutedActive: { value: 'dialogsDraftFgActive', ref: true },
  dialogsUnreadFgActive: { value: 'dialogsBgActive', ref: true },
  dialogsForwardBg: { value: 'dialogsBgActive', ref: true },
  dialogsForwardFg: { value: 'dialogsNameFgActive', ref: true },
  searchedBarBg: { value: '#273845' },
  searchedBarBorder: { value: 'shadowFg', ref: true },
  searchedBarFg: { value: '#86A5BD' },
  topBarBg: { value: 'windowBg', ref: true },
  emojiPanBg: { value: 'windowBg', ref: true },
  emojiPanCategories: { value: '#1F2C36' },
  emojiPanHeaderFg: { value: 'windowSubTextFg', ref: true },
  emojiPanHeaderBg: { value: '#1F2C36f2' },
  stickerPanDeleteBg: { value: '#000000cc' },
  stickerPanDeleteFg: { value: 'windowFgActive', ref: true },
  stickerPreviewBg: { value: '#1F2C36b0' },
  historyTextInFg: { value: 'windowFg', ref: true },
  historyTextOutFg: { value: 'windowFg', ref: true },
  historyCaptionInFg: { value: 'historyTextInFg', ref: true },
  historyCaptionOutFg: { value: 'historyTextOutFg', ref: true },
  historyFileNameInFg: { value: 'historyTextInFg', ref: true },
  historyFileNameOutFg: { value: 'historyTextOutFg', ref: true },
  historyOutIconFg: { value: 'dialogsSentIconFg', ref: true },
  historyOutIconFgSelected: { value: '#149ce6' },
  historyIconFgInverted: { value: 'windowFgActive', ref: true },
  historySendingOutIconFg: { value: '#9dc2d9' },
  historySendingInIconFg: { value: '#a0adb5' },
  historySendingInvertedIconFg: { value: '#ffffffc8' },
  historySystemBg: { value: '#89a0b47f' },
  historySystemBgSelected: { value: '#bbc8d4a2' },
  historySystemFg: { value: 'windowFgActive', ref: true },
  historyUnreadBarBg: { value: '#394650' },
  historyUnreadBarBorder: { value: 'shadowFg', ref: true },
  historyUnreadBarFg: { value: '#538bb4' },
  historyForwardChooseBg: { value: '#0000004c' },
  historyForwardChooseFg: { value: 'windowFgActive', ref: true },
  historyPeer1NameFg: { value: '#C7473E' },
  historyPeer1UserpicBg: { value: '#e17076' },
  historyPeer2NameFg: { value: '#4fad2d' },
  historyPeer2UserpicBg: { value: '#7bc862' },
  historyPeer3NameFg: { value: '#d09306' },
  historyPeer3UserpicBg: { value: '#e5ca77' },
  historyPeer4NameFg: { value: 'windowActiveTextFg', ref: true },
  historyPeer4UserpicBg: { value: '#65aadd' },
  historyPeer5NameFg: { value: '#8544d6' },
  historyPeer5UserpicBg: { value: '#a695e7' },
  historyPeer6NameFg: { value: '#cd4073' },
  historyPeer6UserpicBg: { value: '#ee7aae' },
  historyPeer7NameFg: { value: '#2996ad' },
  historyPeer7UserpicBg: { value: '#6ec9cb' },
  historyPeer8NameFg: { value: '#ce671b' },
  historyPeer8UserpicBg: { value: '#faa774' },
  historyPeerUserpicFg: { value: 'windowFgActive', ref: true },
  historyScrollBarBg: { value: '#267db27a' },
  historyScrollBarBgOver: { value: '#267db2bc' },
  historyScrollBg: { value: '#267db24c' },
  historyScrollBgOver: { value: '#267db26b' },
  msgInBg: { value: 'windowBg', ref: true },
  msgInBgSelected: { value: '#394650' },
  msgOutBg: { value: '#003950' },
  msgOutBgSelected: { value: '#0C5269' },
  msgSelectOverlay: { value: '#358cd44c' },
  msgStickerOverlay: { value: '#358cd47f' },
  msgInServiceFg: { value: 'windowActiveTextFg', ref: true },
  msgInServiceFgSelected: { value: 'windowActiveTextFg', ref: true },
  msgOutServiceFg: { value: 'windowActiveTextFg', ref: true },
  msgOutServiceFgSelected: { value: 'windowActiveTextFg', ref: true },
  msgInShadow: { value: '#144D7B29' },
  msgInShadowSelected: { value: '#548dbb29' },
  msgOutShadow: { value: '#144D7B29' },
  msgOutShadowSelected: { value: '#548dbb29' },
  msgInDateFg: { value: '#525F69' },
  msgInDateFgSelected: { value: '#6a9cc5' },
  msgOutDateFg: { value: '#457795' },
  msgOutDateFgSelected: { value: '#5e92b2' },
  msgServiceFg: { value: '#D5D5D5' },
  msgServiceBg: { value: '#267db27f' },
  msgServiceBgSelected: { value: '#62afdda2' },
  msgInReplyBarColor: { value: 'activeLineFg', ref: true },
  msgInReplyBarSelColor: { value: 'activeLineFg', ref: true },
  msgOutReplyBarColor: { value: 'historyOutIconFg', ref: true },
  msgOutReplyBarSelColor: { value: 'historyOutIconFgSelected', ref: true },
  msgImgReplyBarColor: { value: 'msgServiceFg', ref: true },
  msgInMonoFg: { value: '#2AA198' },
  msgOutMonoFg: { value: '#2AA198' },
  msgDateImgFg: { value: 'msgServiceFg', ref: true },
  msgDateImgBg: { value: '#076CB3B4' },
  msgDateImgBgOver: { value: '#076CB3D4' },
  msgDateImgBgSelected: { value: '#1c4a7187' },
  msgFileThumbLinkInFg: { value: 'lightButtonFg', ref: true },
  msgFileThumbLinkInFgSelected: { value: 'lightButtonFgOver', ref: true },
  msgFileThumbLinkOutFg: { value: 'lightButtonFg', ref: true },
  msgFileThumbLinkOutFgSelected: { value: 'lightButtonFgOver', ref: true },
  msgFileInBg: { value: 'windowBgActive', ref: true },
  msgFileInBgOver: { value: '#4eade3' },
  msgFileInBgSelected: { value: '#51a3d3' },
  msgFileOutBg: { value: 'windowBgActive', ref: true },
  msgFileOutBgOver: { value: '#4eade3' },
  msgFileOutBgSelected: { value: '#51a3d3' },
  msgFile1Bg: { value: '#72b1df' },
  msgFile1BgDark: { value: '#5c9ece' },
  msgFile1BgOver: { value: '#5294c4' },
  msgFile1BgSelected: { value: '#5099d0' },
  msgFile2Bg: { value: '#61b96e' },
  msgFile2BgDark: { value: '#4da859' },
  msgFile2BgOver: { value: '#44a050' },
  msgFile2BgSelected: { value: '#46a07e' },
  msgFile3Bg: { value: '#e47272' },
  msgFile3BgDark: { value: '#cd5b5e' },
  msgFile3BgOver: { value: '#c35154' },
  msgFile3BgSelected: { value: '#9f6a82' },
  msgFile4Bg: { value: '#efc274' },
  msgFile4BgDark: { value: '#e6a561' },
  msgFile4BgOver: { value: '#dc9c5a' },
  msgFile4BgSelected: { value: '#b19d84' },
  msgWaveformInActive: { value: 'windowBgActive', ref: true },
  msgWaveformInActiveSelected: { value: '#51a3d3' },
  msgWaveformInInactive: { value: '#d4dee6' },
  msgWaveformInInactiveSelected: { value: '#9cc1e1' },
  msgWaveformOutActive: { value: 'windowBgActive', ref: true },
  msgWaveformOutActiveSelected: { value: '#51a3d3' },
  msgWaveformOutInactive: { value: '#b3d4e7' },
  msgWaveformOutInactiveSelected: { value: '#87bcdb' },
  msgBotKbOverBgAdd: { value: '#ffffff20' },
  msgBotKbIconFg: { value: 'msgServiceFg', ref: true },
  msgBotKbRippleBg: { value: '#00000020' },
  mediaInFg: { value: 'msgInDateFg', ref: true },
  mediaInFgSelected: { value: 'msgInDateFgSelected', ref: true },
  mediaOutFg: { value: 'msgOutDateFg', ref: true },
  mediaOutFgSelected: { value: 'msgOutDateFgSelected', ref: true },
  youtubePlayIconBg: { value: '#e83131c8' },
  youtubePlayIconFg: { value: 'windowFgActive', ref: true },
  videoPlayIconBg: { value: '#0000007f' },
  videoPlayIconFg: { value: '#ffffff' },
  toastBg: { value: '#000000b2' },
  toastFg: { value: 'windowFgActive', ref: true },
  reportSpamBg: { value: 'emojiPanHeaderBg', ref: true },
  reportSpamFg: { value: 'windowFg', ref: true },
  historyToDownShadow: { value: '#00000040' },
  historyComposeAreaBg: { value: 'msgInBg', ref: true },
  historyComposeAreaFg: { value: 'historyTextInFg', ref: true },
  historyComposeAreaFgService: { value: 'msgInDateFg', ref: true },
  historyComposeIconFg: { value: 'menuIconFg', ref: true },
  historyComposeIconFgOver: { value: 'menuIconFgOver', ref: true },
  historySendIconFg: { value: 'windowBgActive', ref: true },
  historySendIconFgOver: { value: 'windowBgActive', ref: true },
  historyPinnedBg: { value: 'historyComposeAreaBg', ref: true },
  historyReplyBg: { value: 'historyComposeAreaBg', ref: true },
  historyReplyCancelFg: { value: 'cancelIconFg', ref: true },
  historyReplyCancelFgOver: { value: 'cancelIconFgOver', ref: true },
  historyComposeButtonBg: { value: 'historyComposeAreaBg', ref: true },
  historyComposeButtonBgOver: { value: 'nullWindowBgOver', ref: true },
  historyComposeButtonBgRipple: { value: 'windowBgRipple', ref: true },
  overviewCheckBg: { value: '#00000040' },
  overviewCheckFg: { value: 'windowBg', ref: true },
  overviewCheckFgActive: { value: 'windowBg', ref: true },
  overviewPhotoSelectOverlay: { value: '#40ace333' },
  profileStatusFgOver: { value: '#7c99b2' },
  notificationsBoxMonitorFg: { value: 'windowFg', ref: true },
  notificationsBoxScreenBg: { value: 'dialogsBgActive', ref: true },
  notificationSampleUserpicFg: { value: 'windowBgActive', ref: true },
  notificationSampleCloseFg: { value: '#d7d7d7' },
  notificationSampleTextFg: { value: '#d7d7d7' },
  notificationSampleNameFg: { value: '#939393' },
  mainMenuBg: { value: 'windowBg', ref: true },
  mainMenuCoverBg: { value: 'dialogsBgActive', ref: true },
  mainMenuCoverFg: { value: 'windowFgActive', ref: true },
  mediaPlayerBg: { value: 'windowBg', ref: true },
  mediaPlayerActiveFg: { value: 'windowBgActive', ref: true },
  mediaPlayerInactiveFg: { value: 'sliderBgInactive', ref: true },
  mediaPlayerDisabledFg: { value: '#9dd1ef' },
  mediaviewFileBg: { value: 'windowBg', ref: true },
  mediaviewFileNameFg: { value: 'windowFg', ref: true },
  mediaviewFileSizeFg: { value: 'windowSubTextFg', ref: true },
  mediaviewFileRedCornerFg: { value: '#d55959' },
  mediaviewFileYellowCornerFg: { value: '#e8a659' },
  mediaviewFileGreenCornerFg: { value: '#49a957' },
  mediaviewFileBlueCornerFg: { value: '#599dcf' },
  mediaviewFileExtFg: { value: 'activeButtonFg', ref: true },
  mediaviewMenuBg: { value: '#383838' },
  mediaviewMenuBgOver: { value: '#505050' },
  mediaviewMenuBgRipple: { value: '#676767' },
  mediaviewMenuFg: { value: 'windowFgActive', ref: true },
  mediaviewBg: { value: '#222222eb' },
  mediaviewVideoBg: { value: 'imageBg', ref: true },
  mediaviewControlBg: { value: '#0000003c' },
  mediaviewControlFg: { value: 'windowFgActive', ref: true },
  mediaviewCaptionBg: { value: '#11111180' },
  mediaviewCaptionFg: { value: 'mediaviewControlFg', ref: true },
  mediaviewTextLinkFg: { value: '#91d9ff' },
  mediaviewSaveMsgBg: { value: 'toastBg', ref: true },
  mediaviewSaveMsgFg: { value: 'toastFg', ref: true },
  mediaviewPlaybackActive: { value: '#c7c7c7' },
  mediaviewPlaybackInactive: { value: '#252525' },
  mediaviewPlaybackActiveOver: { value: '#ffffff' },
  mediaviewPlaybackInactiveOver: { value: '#474747' },
  mediaviewPlaybackProgressFg: { value: '#ffffffc7' },
  mediaviewPlaybackIconFg: { value: 'mediaviewPlaybackActive', ref: true },
  mediaviewPlaybackIconFgOver: { value: 'mediaviewPlaybackActiveOver', ref: true },
  mediaviewTransparentBg: { value: '#ffffff' },
  mediaviewTransparentFg: { value: '#cccccc' },
  notificationBg: { value: 'windowBg', ref: true },
};

export const def: TelegramTheme = {
  windowBg: { value: '#ffffff' },
  windowFg: { value: '#000000' },
  windowBgOver: { value: '#f1f1f1' },
  windowBgRipple: { value: '#e5e5e5' },
  windowFgOver: { value: 'windowFg', ref: true },
  windowSubTextFg: { value: '#999999' },
  windowSubTextFgOver: { value: '#919191' },
  windowBoldFg: { value: '#222222' },
  windowBoldFgOver: { value: '#222222' },
  windowBgActive: { value: '#40a7e3' },
  windowFgActive: { value: '#ffffff' },
  windowActiveTextFg: { value: '#168acd' },
  windowShadowFg: { value: '#000000' },
  windowShadowFgFallback: { value: '#f1f1f1' },
  shadowFg: { value: '#00000018' },
  slideFadeOutBg: { value: '#0000003c' },
  slideFadeOutShadowFg: { value: 'windowShadowFg', ref: true },
  imageBg: { value: '#000000' },
  imageBgTransparent: { value: '#ffffff' },
  activeButtonBg: { value: 'windowBgActive', ref: true },
  activeButtonBgOver: { value: '#39a5db' },
  activeButtonBgRipple: { value: '#2095d0' },
  activeButtonFg: { value: 'windowFgActive', ref: true },
  activeButtonFgOver: { value: 'activeButtonFg', ref: true },
  activeButtonSecondaryFg: { value: '#cceeff' },
  activeButtonSecondaryFgOver: { value: 'activeButtonSecondaryFg', ref: true },
  activeLineFg: { value: '#37a1de' },
  activeLineFgError: { value: '#e48383' },
  lightButtonBg: { value: 'windowBg', ref: true },
  lightButtonBgOver: { value: '#e3f1fa' },
  lightButtonBgRipple: { value: '#c9e4f6' },
  lightButtonFg: { value: 'windowActiveTextFg', ref: true },
  lightButtonFgOver: { value: 'lightButtonFg', ref: true },
  attentionButtonFg: { value: '#d14e4e' },
  attentionButtonFgOver: { value: '#d14e4e' },
  attentionButtonBgOver: { value: '#fcdfde' },
  attentionButtonBgRipple: { value: '#f4c3c2' },
  outlineButtonBg: { value: 'windowBg', ref: true },
  outlineButtonBgOver: { value: 'lightButtonBgOver', ref: true },
  outlineButtonOutlineFg: { value: 'windowBgActive', ref: true },
  outlineButtonBgRipple: { value: 'lightButtonBgRipple', ref: true },
  menuBg: { value: 'windowBg', ref: true },
  menuBgOver: { value: 'windowBgOver', ref: true },
  menuBgRipple: { value: 'windowBgRipple', ref: true },
  menuIconFg: { value: '#a8a8a8' },
  menuIconFgOver: { value: '#999999' },
  menuSubmenuArrowFg: { value: '#373737' },
  menuFgDisabled: { value: '#cccccc' },
  menuSeparatorFg: { value: '#f1f1f1' },
  scrollBarBg: { value: '#00000053' },
  scrollBarBgOver: { value: '#0000007a' },
  scrollBg: { value: '#0000001a' },
  scrollBgOver: { value: '#0000002c' },
  smallCloseIconFg: { value: '#c7c7c7' },
  smallCloseIconFgOver: { value: '#a3a3a3' },
  radialFg: { value: 'windowFgActive', ref: true },
  radialBg: { value: '#00000056' },
  placeholderFg: { value: 'windowSubTextFg', ref: true },
  placeholderFgActive: { value: '#aaaaaa' },
  inputBorderFg: { value: '#e0e0e0' },
  filterInputBorderFg: { value: '#54c3f3' },
  filterInputInactiveBg: { value: 'windowBgOver', ref: true },
  checkboxFg: { value: '#b3b3b3' },
  sliderBgInactive: { value: '#e1eaef' },
  sliderBgActive: { value: 'windowBgActive', ref: true },
  tooltipBg: { value: '#eef2f5' },
  tooltipFg: { value: '#5d6c80' },
  tooltipBorderFg: { value: '#c9d1db' },
  titleShadow: { value: '#00000003' },
  titleBg: { value: 'windowBgOver', ref: true },
  titleBgActive: { value: 'titleBg', ref: true },
  titleButtonBg: { value: 'titleBg', ref: true },
  titleButtonFg: { value: '#ababab' },
  titleButtonBgOver: { value: '#e5e5e5' },
  titleButtonFgOver: { value: '#9a9a9a' },
  titleButtonBgActive: { value: 'titleButtonBg', ref: true },
  titleButtonFgActive: { value: 'titleButtonFg', ref: true },
  titleButtonBgActiveOver: { value: 'titleButtonBgOver', ref: true },
  titleButtonFgActiveOver: { value: 'titleButtonFgOver', ref: true },
  titleButtonCloseBg: { value: 'titleButtonBg', ref: true },
  titleButtonCloseFg: { value: 'titleButtonFg', ref: true },
  titleButtonCloseBgOver: { value: '#e81123' },
  titleButtonCloseFgOver: { value: 'windowFgActive', ref: true },
  titleButtonCloseBgActive: { value: 'titleButtonCloseBg', ref: true },
  titleButtonCloseFgActive: { value: 'titleButtonCloseFg', ref: true },
  titleButtonCloseBgActiveOver: { value: 'titleButtonCloseBgOver', ref: true },
  titleButtonCloseFgActiveOver: { value: 'titleButtonCloseFgOver', ref: true },
  titleFg: { value: '#acacac' },
  titleFgActive: { value: '#3e3c3e' },
  trayCounterBg: { value: '#f23c34' },
  trayCounterBgMute: { value: '#888888' },
  trayCounterFg: { value: '#ffffff' },
  trayCounterBgMacInvert: { value: '#ffffff' },
  trayCounterFgMacInvert: { value: '#ffffff01' },
  layerBg: { value: '#0000007f' },
  cancelIconFg: { value: 'menuIconFg', ref: true },
  cancelIconFgOver: { value: 'menuIconFgOver', ref: true },
  boxBg: { value: 'windowBg', ref: true },
  boxTextFg: { value: 'windowFg', ref: true },
  boxTextFgGood: { value: '#4ab44a' },
  boxTextFgError: { value: '#d84d4d' },
  boxTitleFg: { value: '#404040' },
  boxSearchBg: { value: 'boxBg', ref: true },
  boxTitleAdditionalFg: { value: '#808080' },
  boxTitleCloseFg: { value: 'cancelIconFg', ref: true },
  boxTitleCloseFgOver: { value: 'cancelIconFgOver', ref: true },
  membersAboutLimitFg: { value: 'windowSubTextFgOver', ref: true },
  contactsBg: { value: 'windowBg', ref: true },
  contactsBgOver: { value: 'windowBgOver', ref: true },
  contactsNameFg: { value: 'boxTextFg', ref: true },
  contactsStatusFg: { value: 'windowSubTextFg', ref: true },
  contactsStatusFgOver: { value: 'windowSubTextFgOver', ref: true },
  contactsStatusFgOnline: { value: 'windowActiveTextFg', ref: true },
  photoCropFadeBg: { value: 'layerBg', ref: true },
  photoCropPointFg: { value: '#ffffff7f' },
  introBg: { value: 'windowBg', ref: true },
  introTitleFg: { value: 'windowBoldFg', ref: true },
  introDescriptionFg: { value: 'windowSubTextFg', ref: true },
  introErrorFg: { value: 'windowSubTextFg', ref: true },
  introCoverTopBg: { value: '#0f89d0' },
  introCoverBottomBg: { value: '#39b0f0' },
  introCoverIconsFg: { value: '#5ec6ff' },
  introCoverPlaneTrace: { value: '#5ec6ff69' },
  introCoverPlaneInner: { value: '#c6d8e8' },
  introCoverPlaneOuter: { value: '#a1bed4' },
  introCoverPlaneTop: { value: '#ffffff' },
  dialogsMenuIconFg: { value: 'menuIconFg', ref: true },
  dialogsMenuIconFgOver: { value: 'menuIconFgOver', ref: true },
  dialogsBg: { value: 'windowBg', ref: true },
  dialogsNameFg: { value: 'windowBoldFg', ref: true },
  dialogsChatIconFg: { value: 'dialogsNameFg', ref: true },
  dialogsDateFg: { value: 'windowSubTextFg', ref: true },
  dialogsTextFg: { value: 'windowSubTextFg', ref: true },
  dialogsTextFgService: { value: 'windowActiveTextFg', ref: true },
  dialogsDraftFg: { value: '#dd4b39' },
  dialogsVerifiedIconBg: { value: 'windowBgActive', ref: true },
  dialogsVerifiedIconFg: { value: 'windowFgActive', ref: true },
  dialogsSendingIconFg: { value: '#c1c1c1' },
  dialogsSentIconFg: { value: '#5dc452' },
  dialogsUnreadBg: { value: 'windowBgActive', ref: true },
  dialogsUnreadBgMuted: { value: '#bbbbbb' },
  dialogsUnreadFg: { value: 'windowFgActive', ref: true },
  dialogsBgOver: { value: 'windowBgOver', ref: true },
  dialogsNameFgOver: { value: 'windowBoldFgOver', ref: true },
  dialogsChatIconFgOver: { value: 'dialogsNameFgOver', ref: true },
  dialogsDateFgOver: { value: 'windowSubTextFgOver', ref: true },
  dialogsTextFgOver: { value: 'windowSubTextFgOver', ref: true },
  dialogsTextFgServiceOver: { value: 'dialogsTextFgService', ref: true },
  dialogsDraftFgOver: { value: 'dialogsDraftFg', ref: true },
  dialogsVerifiedIconBgOver: { value: 'dialogsVerifiedIconBg', ref: true },
  dialogsVerifiedIconFgOver: { value: 'dialogsVerifiedIconFg', ref: true },
  dialogsSendingIconFgOver: { value: 'dialogsSendingIconFg', ref: true },
  dialogsSentIconFgOver: { value: 'dialogsSentIconFg', ref: true },
  dialogsUnreadBgOver: { value: 'dialogsUnreadBg', ref: true },
  dialogsUnreadBgMutedOver: { value: 'dialogsUnreadBgMuted', ref: true },
  dialogsUnreadFgOver: { value: 'dialogsUnreadFg', ref: true },
  dialogsBgActive: { value: '#419fd9' },
  dialogsNameFgActive: { value: 'windowFgActive', ref: true },
  dialogsChatIconFgActive: { value: 'dialogsNameFgActive', ref: true },
  dialogsDateFgActive: { value: 'windowFgActive', ref: true },
  dialogsTextFgActive: { value: 'windowFgActive', ref: true },
  dialogsTextFgServiceActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsDraftFgActive: { value: '#c6e1f7' },
  dialogsVerifiedIconBgActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsVerifiedIconFgActive: { value: 'dialogsBgActive', ref: true },
  dialogsSendingIconFgActive: { value: '#ffffff99' },
  dialogsSentIconFgActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsUnreadBgActive: { value: 'dialogsTextFgActive', ref: true },
  dialogsUnreadBgMutedActive: { value: 'dialogsDraftFgActive', ref: true },
  dialogsUnreadFgActive: { value: 'dialogsBgActive', ref: true },
  dialogsForwardBg: { value: 'dialogsBgActive', ref: true },
  dialogsForwardFg: { value: 'dialogsNameFgActive', ref: true },
  searchedBarBg: { value: 'windowBgOver', ref: true },
  searchedBarFg: { value: 'windowSubTextFgOver', ref: true },
  topBarBg: { value: 'windowBg', ref: true },
  emojiPanBg: { value: 'windowBg', ref: true },
  emojiPanCategories: { value: '#f7f7f7', ref: true },
  emojiPanHeaderFg: { value: 'windowSubTextFg', ref: true },
  emojiPanHeaderBg: { value: '#fffffff2', ref: true },
  stickerPanDeleteBg: { value: '#000000cc' },
  stickerPanDeleteFg: { value: 'windowFgActive', ref: true },
  stickerPreviewBg: { value: '#ffffffb0' },
  historyTextInFg: { value: 'windowFg', ref: true },
  historyTextOutFg: { value: 'windowFg', ref: true },
  historyCaptionInFg: { value: 'historyTextInFg', ref: true },
  historyCaptionOutFg: { value: 'historyTextOutFg', ref: true },
  historyFileNameInFg: { value: 'historyTextInFg', ref: true },
  historyFileNameOutFg: { value: 'historyTextOutFg', ref: true },
  historyOutIconFg: { value: 'dialogsSentIconFg', ref: true },
  historyOutIconFgSelected: { value: '#4da79f' },
  historyIconFgInverted: { value: 'windowFgActive', ref: true },
  historySendingOutIconFg: { value: '#98d292' },
  historySendingInIconFg: { value: '#a0adb5' },
  historySendingInvertedIconFg: { value: '#ffffffc8' },
  historyUnreadBarBg: { value: '#fcfbfa' },
  historyUnreadBarBorder: { value: 'shadowFg', ref: true },
  historyUnreadBarFg: { value: '#538bb4' },
  historyForwardChooseBg: { value: '#0000004c' },
  historyForwardChooseFg: { value: 'windowFgActive', ref: true },
  historyPeer1NameFg: { value: '#c03d33' },
  historyPeer1UserpicBg: { value: '#e17076' },
  historyPeer2NameFg: { value: '#4fad2d' },
  historyPeer2UserpicBg: { value: '#7bc862' },
  historyPeer3NameFg: { value: '#d09306' },
  historyPeer3UserpicBg: { value: '#e5ca77' },
  historyPeer4NameFg: { value: 'windowActiveTextFg', ref: true },
  historyPeer4UserpicBg: { value: '#65aadd' },
  historyPeer5NameFg: { value: '#8544d6' },
  historyPeer5UserpicBg: { value: '#a695e7' },
  historyPeer6NameFg: { value: '#cd4073' },
  historyPeer6UserpicBg: { value: '#ee7aae' },
  historyPeer7NameFg: { value: '#2996ad' },
  historyPeer7UserpicBg: { value: '#6ec9cb' },
  historyPeer8NameFg: { value: '#ce671b' },
  historyPeer8UserpicBg: { value: '#faa774' },
  historyPeerUserpicFg: { value: 'windowFgActive', ref: true },
  historyScrollBarBg: { value: '#517c417a' },
  historyScrollBarBgOver: { value: '#517c41bc' },
  historyScrollBg: { value: '#517c414c' },
  historyScrollBgOver: { value: '#517c416b' },
  msgInBg: { value: 'windowBg', ref: true },
  msgInBgSelected: { value: '#c2dcf2' },
  msgOutBg: { value: '#effdde' },
  msgOutBgSelected: { value: '#b7dbdb' },
  msgSelectOverlay: { value: '#358cd44c' },
  msgStickerOverlay: { value: '#358cd47f' },
  msgInServiceFg: { value: 'windowActiveTextFg', ref: true },
  msgInServiceFgSelected: { value: 'windowActiveTextFg', ref: true },
  msgOutServiceFg: { value: '#3a8e26' },
  msgOutServiceFgSelected: { value: '#367570' },
  msgInShadow: { value: '#748ea229' },
  msgInShadowSelected: { value: '#548dbb29' },
  msgOutShadow: { value: '#3ac34740' },
  msgOutShadowSelected: { value: '#37a78e40' },
  msgInDateFg: { value: '#a0acb6' },
  msgInDateFgSelected: { value: '#6a9cc5' },
  msgOutDateFg: { value: '#6cc264' },
  msgOutDateFgSelected: { value: '#50a79c' },
  msgServiceFg: { value: 'windowFgActive', ref: true },
  msgServiceBg: { value: '#517c417f' },
  msgServiceBgSelected: { value: '#96b38ba2' },
  msgInReplyBarColor: { value: 'activeLineFg', ref: true },
  msgInReplyBarSelColor: { value: 'activeLineFg', ref: true },
  msgOutReplyBarColor: { value: 'historyOutIconFg', ref: true },
  msgOutReplyBarSelColor: { value: 'historyOutIconFgSelected', ref: true },
  msgImgReplyBarColor: { value: 'msgServiceFg', ref: true },
  msgInMonoFg: { value: '#4e7391' },
  msgOutMonoFg: { value: '#469165' },
  msgDateImgFg: { value: 'msgServiceFg', ref: true },
  msgDateImgBg: { value: '#00000054' },
  msgDateImgBgOver: { value: '#00000074' },
  msgDateImgBgSelected: { value: '#1c4a7187' },
  msgFileThumbLinkInFg: { value: 'lightButtonFg', ref: true },
  msgFileThumbLinkInFgSelected: { value: 'lightButtonFgOver', ref: true },
  msgFileThumbLinkOutFg: { value: '#5eba5b' },
  msgFileThumbLinkOutFgSelected: { value: '#31a298' },
  msgFileInBg: { value: 'windowBgActive', ref: true },
  msgFileInBgOver: { value: '#4eade3' },
  msgFileInBgSelected: { value: '#51a3d3' },
  msgFileOutBg: { value: '#78c67f' },
  msgFileOutBgOver: { value: '#6bc272' },
  msgFileOutBgSelected: { value: '#5fb389' },
  msgFile1Bg: { value: '#72b1df' },
  msgFile1BgDark: { value: '#5c9ece' },
  msgFile1BgOver: { value: '#5294c4' },
  msgFile1BgSelected: { value: '#5099d0' },
  msgFile2Bg: { value: '#61b96e' },
  msgFile2BgDark: { value: '#4da859' },
  msgFile2BgOver: { value: '#44a050' },
  msgFile2BgSelected: { value: '#46a07e' },
  msgFile3Bg: { value: '#e47272' },
  msgFile3BgDark: { value: '#cd5b5e' },
  msgFile3BgOver: { value: '#c35154' },
  msgFile3BgSelected: { value: '#9f6a82' },
  msgFile4Bg: { value: '#efc274' },
  msgFile4BgDark: { value: '#e6a561' },
  msgFile4BgOver: { value: '#dc9c5a' },
  msgFile4BgSelected: { value: '#b19d84' },
  historyFileInIconFg: { value: 'msgInBg', ref: true },
  historyFileInIconFgSelected: { value: 'msgInBgSelected', ref: true },
  historyFileInRadialFg: { value: 'historyFileInIconFg', ref: true },
  historyFileInRadialFgSelected: { value: 'historyFileInIconFgSelected', ref: true },
  historyFileOutIconFg: { value: 'msgOutBg', ref: true },
  historyFileOutIconFgSelected: { value: 'msgOutBgSelected', ref: true },
  historyFileOutRadialFg: { value: 'historyFileOutIconFg', ref: true },
  historyFileOutRadialFgSelected: { value: 'historyFileOutIconFgSelected', ref: true },
  historyFileThumbIconFg: { value: 'msgInBg', ref: true },
  historyFileThumbIconFgSelected: { value: 'msgInBgSelected', ref: true },
  historyFileThumbRadialFg: { value: 'historyFileThumbIconFg', ref: true },
  historyFileThumbRadialFgSelected: { value: 'historyFileThumbIconFgSelected', ref: true },
  msgWaveformInActive: { value: 'windowBgActive', ref: true },
  msgWaveformInActiveSelected: { value: '#51a3d3' },
  msgWaveformInInactive: { value: '#d4dee6' },
  msgWaveformInInactiveSelected: { value: '#9cc1e1' },
  msgWaveformOutActive: { value: '#78c67f' },
  msgWaveformOutActiveSelected: { value: '#6badad' },
  msgWaveformOutInactive: { value: '#b3e2b4' },
  msgWaveformOutInactiveSelected: { value: '#91c3c3' },
  msgBotKbOverBgAdd: { value: '#ffffff20' },
  msgBotKbIconFg: { value: 'msgServiceFg', ref: true },
  msgBotKbRippleBg: { value: '#00000020' },
  mediaInFg: { value: 'msgInDateFg', ref: true },
  mediaInFgSelected: { value: 'msgInDateFgSelected', ref: true },
  mediaOutFg: { value: 'msgOutDateFg', ref: true },
  mediaOutFgSelected: { value: 'msgOutDateFgSelected', ref: true },
  youtubePlayIconBg: { value: '#e83131c8' },
  youtubePlayIconFg: { value: 'windowFgActive', ref: true },
  videoPlayIconBg: { value: '#0000007f' },
  videoPlayIconFg: { value: '#ffffff' },
  toastBg: { value: '#000000b2' },
  toastFg: { value: 'windowFgActive', ref: true },
  reportSpamBg: { value: 'emojiPanHeaderBg', ref: true },
  reportSpamFg: { value: 'windowFg', ref: true },
  historyToDownBg: { value: 'windowBg', ref: true },
  historyToDownBgOver: { value: 'windowBgOver', ref: true },
  historyToDownBgRipple: { value: 'windowBgRipple', ref: true },
  historyToDownFg: { value: 'menuIconFg', ref: true },
  historyToDownFgOver: { value: 'menuIconFgOver', ref: true },
  historyToDownShadow: { value: '#00000040' },
  historyComposeAreaBg: { value: 'msgInBg', ref: true },
  historyComposeAreaFg: { value: 'historyTextInFg', ref: true },
  historyComposeAreaFgService: { value: 'msgInDateFg', ref: true },
  historyComposeIconFg: { value: 'menuIconFg', ref: true },
  historyComposeIconFgOver: { value: 'menuIconFgOver', ref: true },
  historySendIconFg: { value: 'windowBgActive', ref: true },
  historySendIconFgOver: { value: 'windowBgActive', ref: true },
  historyPinnedBg: { value: 'historyComposeAreaBg', ref: true },
  historyReplyBg: { value: 'historyComposeAreaBg', ref: true },
  historyReplyIconFg: { value: 'windowBgActive', ref: true },
  historyReplyCancelFg: { value: 'cancelIconFg', ref: true },
  historyReplyCancelFgOver: { value: 'cancelIconFgOver', ref: true },
  historyComposeButtonBg: { value: 'historyComposeAreaBg', ref: true },
  historyComposeButtonBgOver: { value: 'windowBgOver', ref: true },
  historyComposeButtonBgRipple: { value: 'windowBgRipple', ref: true },
  overviewCheckBg: { value: '#00000040' },
  overviewCheckFg: { value: 'windowBg', ref: true },
  overviewCheckFgActive: { value: 'windowBg', ref: true },
  overviewPhotoSelectOverlay: { value: '#40ace333' },
  profileStatusFgOver: { value: '#7c99b2' },
  profileVerifiedCheckBg: { value: 'windowBgActive', ref: true },
  profileVerifiedCheckFg: { value: 'windowFgActive', ref: true },
  profileAdminStartFg: { value: 'windowBgActive', ref: true },
  notificationsBoxMonitorFg: { value: 'windowFg', ref: true },
  notificationsBoxScreenBg: { value: 'dialogsBgActive', ref: true },
  notificationSampleUserpicFg: { value: 'windowBgActive', ref: true },
  notificationSampleCloseFg: { value: '#d7d7d7', ref: true },
  notificationSampleTextFg: { value: '#d7d7d7', ref: true },
  notificationSampleNameFg: { value: '#939393', ref: true },
  mainMenuBg: { value: 'windowBg', ref: true },
  mainMenuCoverBg: { value: 'dialogsBgActive', ref: true },
  mainMenuCoverFg: { value: 'windowFgActive', ref: true },
  mediaPlayerBg: { value: 'windowBg', ref: true },
  mediaPlayerActiveFg: { value: 'windowBgActive', ref: true },
  mediaPlayerInactiveFg: { value: 'sliderBgInactive', ref: true },
  mediaPlayerDisabledFg: { value: '#9dd1ef' },
  mediaviewFileBg: { value: 'windowBg', ref: true },
  mediaviewFileNameFg: { value: 'windowFg', ref: true },
  mediaviewFileSizeFg: { value: 'windowSubTextFg', ref: true },
  mediaviewFileRedCornerFg: { value: '#d55959' },
  mediaviewFileYellowCornerFg: { value: '#e8a659' },
  mediaviewFileGreenCornerFg: { value: '#49a957' },
  mediaviewFileBlueCornerFg: { value: '#599dcf' },
  mediaviewFileExtFg: { value: 'activeButtonFg', ref: true },
  mediaviewMenuBg: { value: '#383838' },
  mediaviewMenuBgOver: { value: '#505050' },
  mediaviewMenuBgRipple: { value: '#676767' },
  mediaviewMenuFg: { value: 'windowFgActive', ref: true },
  mediaviewBg: { value: '#222222eb' },
  mediaviewVideoBg: { value: 'imageBg', ref: true },
  mediaviewControlBg: { value: '#0000003c' },
  mediaviewControlFg: { value: 'windowFgActive', ref: true },
  mediaviewCaptionBg: { value: '#11111180' },
  mediaviewCaptionFg: { value: 'mediaviewControlFg', ref: true },
  mediaviewTextLinkFg: { value: '#91d9ff' },
  mediaviewSaveMsgBg: { value: 'toastBg', ref: true },
  mediaviewSaveMsgFg: { value: 'toastFg', ref: true },
  mediaviewPlaybackActive: { value: '#c7c7c7' },
  mediaviewPlaybackInactive: { value: '#252525' },
  mediaviewPlaybackActiveOver: { value: '#ffffff' },
  mediaviewPlaybackInactiveOver: { value: '#474747' },
  mediaviewPlaybackProgressFg: { value: '#ffffffc7' },
  mediaviewPlaybackIconFg: { value: 'mediaviewPlaybackActive', ref: true },
  mediaviewPlaybackIconFgOver: { value: 'mediaviewPlaybackActiveOver', ref: true },
  mediaviewTransparentBg: { value: '#ffffff' },
  mediaviewTransparentFg: { value: '#cccccc' },
  notificationBg: { value: 'windowBg', ref: true }
};